### ISSUE TITLE
There may be an error in the models.py file

### ISSUE THREAD

**Issue by yurkoff-mv** [BM-K/KoDiffCSE#1]
Hello.
In the **models.py** file, lines `75-83` take only the 'source' part of the input. I assume that in the first case (line `75`) the `'z1_masked_input'` part should be taken, in the second case (line `80`) the `'z2_masked_input'` part should be taken. Is it so?

**Comment by BM-K** [comment]
The key ingredient to get this to work with identical positive pairs is through the use of independently sampled dropout masks for $x_i$ and $x^+_i$. Therefor this code works fine.
The generator receives `z1_masked_input` and `z2_masked_input` as an input.

**Comment by yurkoff-mv** [comment]
It turns out that the encoder is in the train state?
How are negative sentence samples obtained?
And yet, have you tried to freeze all layers of the BERT/RoBERTa model except for the last one and train only it?

**Comment by BM-K** [comment]
1. It turns out that the encoder is in the train state?
    -> I didn't understand your question.
2. How are negative sentence samples obtained?
    -> Negative samples are obtained by in-batch negative sampling method.
3. And yet, have you tried to freeze all layers of the BERT/RoBERTa model except for the last one and train only it?
    -> Didn't try.

**Comment by yurkoff-mv** [comment]
1. A torch model can be in eval and train states. In the train state, Dropout is enabled.
2. Now I understand.
Thanks for your replies.

**Comment by BM-K** [comment]
In the `/model/diffcse/processor.py` file,  lines `129` and `161` set model to training or evaluation states.

**Comment by yurkoff-mv** [comment]
Yes, now I have seen. Thank you.
